[build-system]
requires = ["uv-build"]
build-backend = "uv_build"

[project]
name = "ml-pipeline-e2e-practica"
version = "0.1.0"
description = "Taller de Data Science seguro contra data leakage"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
	"pandas",
	"scikit-learn",
	"numpy",
	"jupyter",
	"matplotlib",
]
